package pe.edu.upeu.navegationjpc.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

val green_primaryLight = Color(0xFF415F91)
val green_onPrimaryLight = Color(0xFFFFFFFF)
val green_primaryContainerLight = Color(0xFFD6E3FF)
val green_onPrimaryContainerLight = Color(0xFF284777)
val green_secondaryLight = Color(0xFF565F71)
val green_onSecondaryLight = Color(0xFFFFFFFF)
val green_secondaryContainerLight = Color(0xFFDAE2F9)
val green_onSecondaryContainerLight = Color(0xFF3E4759)
val green_tertiaryLight = Color(0xFF705575)
val green_onTertiaryLight = Color(0xFFFFFFFF)
val green_tertiaryContainerLight = Color(0xFFFAD8FD)
val green_onTertiaryContainerLight = Color(0xFF573E5C)
val green_errorLight = Color(0xFFBA1A1A)
val green_onErrorLight = Color(0xFFFFFFFF)
val green_errorContainerLight = Color(0xFFFFDAD6)
val green_onErrorContainerLight = Color(0xFF93000A)
val green_backgroundLight = Color(0xFFF9F9FF)
val green_onBackgroundLight = Color(0xFF191C20)
val green_surfaceLight = Color(0xFFF9F9FF)
val green_onSurfaceLight = Color(0xFF191C20)
val green_surfaceVariantLight = Color(0xFFE0E2EC)
val green_onSurfaceVariantLight = Color(0xFF44474E)
val green_outlineLight = Color(0xFF74777F)
val green_outlineVariantLight = Color(0xFFC4C6D0)
val green_scrimLight = Color(0xFF000000)
val green_inverseSurfaceLight = Color(0xFF2E3036)
val green_inverseOnSurfaceLight = Color(0xFFF0F0F7)
val green_inversePrimaryLight = Color(0xFFAAC7FF)
val green_surfaceDimLight = Color(0xFFD9D9E0)
val green_surfaceBrightLight = Color(0xFFF9F9FF)
val green_surfaceContainerLowestLight = Color(0xFFFFFFFF)
val green_surfaceContainerLowLight = Color(0xFFF3F3FA)
val green_surfaceContainerLight = Color(0xFFEDEDF4)
val green_surfaceContainerHighLight = Color(0xFFE7E8EE)
val green_surfaceContainerHighestLight = Color(0xFFE2E2E9)


val green_primaryDark = Color(0xFFAAC7FF)
val green_onPrimaryDark = Color(0xFF0A305F)
val green_primaryContainerDark = Color(0xFF284777)
val green_onPrimaryContainerDark = Color(0xFFD6E3FF)
val green_secondaryDark = Color(0xFFBEC6DC)
val green_onSecondaryDark = Color(0xFF283141)
val green_secondaryContainerDark = Color(0xFF3E4759)
val green_onSecondaryContainerDark = Color(0xFFDAE2F9)
val green_tertiaryDark = Color(0xFFDDBCE0)
val green_onTertiaryDark = Color(0xFF3F2844)
val green_tertiaryContainerDark = Color(0xFF573E5C)
val green_onTertiaryContainerDark = Color(0xFFFAD8FD)
val green_errorDark = Color(0xFFFFB4AB)
val green_onErrorDark = Color(0xFF690005)
val green_errorContainerDark = Color(0xFF93000A)
val green_onErrorContainerDark = Color(0xFFFFDAD6)
val green_backgroundDark = Color(0xFF111318)
val green_onBackgroundDark = Color(0xFFE2E2E9)
val green_surfaceDark = Color(0xFF111318)
val green_onSurfaceDark = Color(0xFFE2E2E9)
val green_surfaceVariantDark = Color(0xFF44474E)
val green_onSurfaceVariantDark = Color(0xFFC4C6D0)
val green_outlineDark = Color(0xFF8E9099)
val green_outlineVariantDark = Color(0xFF44474E)
val green_scrimDark = Color(0xFF000000)
val green_inverseSurfaceDark = Color(0xFFE2E2E9)
val green_inverseOnSurfaceDark = Color(0xFF2E3036)
val green_inversePrimaryDark = Color(0xFF415F91)
val green_surfaceDimDark = Color(0xFF111318)
val green_surfaceBrightDark = Color(0xFF37393E)
val green_surfaceContainerLowestDark = Color(0xFF0C0E13)
val green_surfaceContainerLowDark = Color(0xFF191C20)
val green_surfaceContainerDark = Color(0xFF1D2024)
val green_surfaceContainerHighDark = Color(0xFF282A2F)
val green_surfaceContainerHighestDark = Color(0xFF33353A)